### ISSUE TITLE
two SIGFPE found when testing with Debug spring

### ISSUE THREAD

**Issue by cleanrock** [rlcevg/CircuitAI#19]
Spring 103.0.1-519-g91b0000b2 develop (Debug Signal-NaNs)

SIGFPE in CThreatMap::GetUnitThreat, sqrtf dislikes negative values.

```
(gdb) bt
#0  0x00007f150c7db2b9 in sqrtf () from /usr/lib/libm.so.6
#1  0x00007f14e9b7b6f6 in circuit::CThreatMap::GetUnitThreat (this=0x336fd510, unit=0x30468700)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/terrain/ThreatMap.cpp:391
#2  0x00007f14e9b00653 in circuit::CRetreatTask::Execute (this=0x30be0bc0, unit=0x30468700)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/task/RetreatTask.cpp:124
#3  0x00007f14e9b029e6 in circuit::ITaskManager::AssignTask (this=0x372c9828, unit=0x30468700, task=0x30be0bc0)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/task/TaskManager.cpp:32
#4  0x00007f14e9b21f47 in circuit::IFighterTask::OnUnitDamaged (this=0x3310e60, unit=0x30468700, attacker=0x31318960)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/task/fighter/FighterTask.cpp:115

(gdb) f 1
#1  0x00007f14e9b7b6f6 in circuit::CThreatMap::GetUnitThreat (this=0x336fd510, unit=0x30468700)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/terrain/ThreatMap.cpp:391
391		return unit->GetDamage() * sqrtf(health);  // / unit->GetUnit()->GetMaxHealth();

(gdb) p health 
$1 = -88

(gdb) p unit->shield
$3 = (springai::Weapon *) 0x0

```

SGIFPE in CSetupData::ParseSetupScript (engine way) due to CAllyTeam::SBox not initialised.
I have no startrect in my start script so startbox.right  *= width; caused SIGFPE.

Here are my quick fix for these two SIGFPE:

```
CircuitAI]$ git diff
diff --git a/src/circuit/terrain/ThreatMap.cpp b/src/circuit/terrain/ThreatMap.cpp
index 5d061d7..0306c67 100644
--- a/src/circuit/terrain/ThreatMap.cpp
+++ b/src/circuit/terrain/ThreatMap.cpp
@@ -388,7 +388,7 @@ float CThreatMap::GetThreatAt(CCircuitUnit* unit, const AIFloat3& position) cons
 float CThreatMap::GetUnitThreat(CCircuitUnit* unit) const
 {
        float health = unit->GetUnit()->GetHealth() + unit->GetShieldPower() * 2.0f;
-       return unit->GetDamage() * sqrtf(health);  // / unit->GetUnit()->GetMaxHealth();
+       return unit->GetDamage() * sqrtf(std::max(health, 0.f));  // / unit->GetUnit()->GetMaxHealth();
 }
 
 void CThreatMap::AddEnemyUnit(const CEnemyUnit* e)
diff --git a/src/circuit/unit/AllyTeam.h b/src/circuit/unit/AllyTeam.h
index 864b995..ee78bd2 100644
--- a/src/circuit/unit/AllyTeam.h
+++ b/src/circuit/unit/AllyTeam.h
@@ -33,6 +33,7 @@ public:
        using Units = std::map<CCircuitUnit::Id, CCircuitUnit*>;
        using TeamIds = std::unordered_set<Id>;
        union SBox {
+               SBox(): edge{0.f,0.f,0.f,0.f} {}
                struct {
                        float bottom;
                        float left;

```

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/37ab0cf5d9c78166d721565c2d03a650a6e64539
